"""Add nopCommerce models

Revision ID: 26ae8fb2a4c7
Revises: 24c40d2cf7f5
Create Date: 2026-03-21 16:04:58.880476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ae8fb2a4c7'
down_revision: Union[str, Sequence[str], None] = '24c40d2cf7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_on_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_on_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('listing_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_attributes_id'), 'listing_attributes', ['id'], unique=False)
    op.create_table('shipping_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_methods_id'), 'shipping_methods', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('zip_postal_code', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_on_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('listing_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_adjustment', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_pre_selected', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['listing_attributes.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_attribute_values_id'), 'listing_attribute_values', ['id'], unique=False)
    op.add_column('listings', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('sustainability_tags', sa.JSON(), nullable=True))
    op.add_column('listings', sa.Column('embedding', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'listings', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'listings', 'brands', ['brand_id'], ['id'])
    op.add_column('orders', sa.Column('shipping_address_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_method_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('order_tax', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('order_discount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'shipping_methods', ['shipping_method_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'addresses', ['shipping_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'order_discount')
    op.drop_column('orders', 'order_tax')
    op.drop_column('orders', 'shipping_method_id')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'embedding')
    op.drop_column('listings', 'sustainability_tags')
    op.drop_column('listings', 'brand_id')
    op.drop_column('listings', 'category_id')
    op.drop_index(op.f('ix_listing_attribute_values_id'), table_name='listing_attribute_values')
    op.drop_table('listing_attribute_values')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_shipping_methods_id'), table_name='shipping_methods')
    op.drop_table('shipping_methods')
    op.drop_index(op.f('ix_listing_attributes_id'), table_name='listing_attributes')
    op.drop_table('listing_attributes')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
